conf_path: conf/embeddings_validation_baselines_supervised.yaml
environment: 
  work_dir: embeddings_validation.work
target: 
  file_name: ${hydra:runtime.cwd}/data/clients_target.csv
  cols_id: 
    - client_id
  cols_id_type: 
    - str
  col_target: age
split: 
  fit_ids: true
  train_id: 
    file_name: ${hydra:runtime.cwd}/data/clients_target.csv
  test_id: 
    file_name: ${hydra:runtime.cwd}/data/test_ids.csv
  cv_split_count: 5
  is_stratify: true
  random_state: 42
models: 
  linear: 
    enabled: false
    model:
      _target_: sklearn.linear_model.LogisticRegression
    cpu_count: 1
    preprocessing: 
      - _target_: sklearn.preprocessing.MaxAbsScaler

  lgbm: 
    enabled: true
    model:
      _target_: lightgbm.LGBMClassifier
      n_estimators: 1000
      boosting_type: gbdt
      objective: multiclass
      num_class: 4
      metric: multi_error
      subsample: 0.5
      subsample_freq: 1
      learning_rate: 0.05
      feature_fraction: 0.75
      colsample_bytree: null
      max_depth: 6
      lambda_l1: 1
      reg_alpha: null
      lambda_l2: 1
      reg_lambda: null
      min_data_in_leaf: 50
      min_child_samples: null
      num_leaves: 50
      random_state: 42
      n_jobs: 6
    cpu_count: 6
    preprocessing: 
      - _target_: sklearn.preprocessing.MaxAbsScaler

  xgb: 
    enabled: false
    model:
      _target_: xgboost.XGBClassifier
      n_jobs: 4
      objective: multi:softprob
      num_class: 4
      seed: 42
      n_estimators: 300
    cpu_count: 4
    preprocessing: 
      - _target_: sklearn.preprocessing.MaxAbsScaler

metrics: 
  accuracy: 
    enabled: true
    score_func: sklearn.metrics.accuracy_score
    scorer_params: 
      needs_proba: false
report_file: ${hydra:runtime.cwd}/results/scenario_x5_baselines_supervised.txt
features: {}
external_scores: 
  fit_target: ${hydra:runtime.cwd}/results/fit_target_results.json
  mles_finetuning: ${hydra:runtime.cwd}/results/mles_finetuning_results.json
  cpc_finetuning: ${hydra:runtime.cwd}/results/cpc_finetuning_results.json
  rtd_finetuning: ${hydra:runtime.cwd}/results/rtd_finetuning_results.json
  barlow_twins_finetuning: ${hydra:runtime.cwd}/results/barlow_twins_finetuning_results.json
report: 
  is_check_train: false
  error_handling: fail
  print_all_metrics: false
  metrics: 
    accuracy: 
      float_format: "{:.3f}"
      baseline_key: 
        - nn
        - target_scores
      split_columns: true
