conf_path: conf/embeddings_validation_baselines_unsupervised.yaml
environment: 
  work_dir: embeddings_validation.work
target: 
  file_name: ${hydra:runtime.cwd}/data/clients_target.csv
  cols_id: 
    - client_id
  cols_id_type: 
    - str
  col_target: age
split: 
  fit_ids: true
  train_id: 
    file_name: ${hydra:runtime.cwd}/data/clients_target.csv
  test_id: 
    file_name: ${hydra:runtime.cwd}/data/test_ids.csv
  cv_split_count: 5
  is_stratify: true
  random_state: 42
models: 
  linear: 
    enabled: false
    model:
      _target_: sklearn.linear_model.LogisticRegression
    cpu_count: 1
    preprocessing: 
      - _target_: sklearn.preprocessing.MaxAbsScaler

  lgbm: 
    enabled: true
    model:
      _target_: lightgbm.LGBMClassifier
      n_estimators: 1000
      boosting_type: gbdt
      objective: multiclass
      num_class: 4
      metric: multi_error
      subsample: 0.5
      subsample_freq: 1
      learning_rate: 0.05
      feature_fraction: 0.75
      colsample_bytree: null
      max_depth: 6
      lambda_l1: 1
      reg_alpha: null
      lambda_l2: 1
      reg_lambda: null
      min_data_in_leaf: 50
      min_child_samples: null
      num_leaves: 50
      random_state: 42
      n_jobs: 6
    cpu_count: 6
    preprocessing: 
      - _target_: sklearn.preprocessing.MaxAbsScaler

  xgb: 
    enabled: false
    model:
      _target_: xgboost.XGBClassifier
      n_jobs: 4
      objective: multi:softprob
      num_class: 4
      seed: 42
      n_estimators: 300
    cpu_count: 4
    preprocessing: 
      - _target_: sklearn.preprocessing.MaxAbsScaler

metrics: 
  accuracy: 
    enabled: true
    score_func: sklearn.metrics.accuracy_score
    scorer_params: 
      needs_proba: false
report_file: ${hydra:runtime.cwd}/results/scenario_x5_baselines_unsupervised.txt
features: 
  baseline: 
    enabled: true
    read_params: 
      file_name: ${hydra:runtime.cwd}/data/agg_feat_embed.pickle
    target_options: {}
  random_encoder: 
    enabled: true
    read_params: 
      file_name: ${hydra:runtime.cwd}/data/random_embeddings.pickle
    target_options: {}
  mles_embeddings: 
    enabled: true
    read_params: 
      file_name: ${hydra:runtime.cwd}/data/mles_embeddings.pickle
    target_options: {}
  cpc_embeddings: 
    enabled: true
    read_params: 
      file_name: ${hydra:runtime.cwd}/data/cpc_embeddings.pickle
    target_options: {}
  sop_embeddings: 
    enabled: true
    read_params: 
      file_name: ${hydra:runtime.cwd}/data/sop_embeddings.pickle
    target_options: {}
  nsp_embeddings: 
    enabled: true
    read_params: 
      file_name: ${hydra:runtime.cwd}/data/nsp_embeddings.pickle
    target_options: {}
  rtd_embeddings: 
    enabled: true
    read_params: 
      file_name: ${hydra:runtime.cwd}/data/rtd_embeddings.pickle
    target_options: {}
  mles2_embeddings: 
    enabled: true
    read_params: 
      file_name: ${hydra:runtime.cwd}/data/mles2_embeddings.pickle
    target_options: {}
  barlow_twins_embeddings: 
    enabled: true
    read_params: 
      file_name: ${hydra:runtime.cwd}/data/barlow_twins_embeddings.pickle
    target_options: {}
external_scores: {}
report: 
  is_check_train: false
  error_handling: fail
  print_all_metrics: false
  metrics: 
    accuracy: 
      float_format: "{:.3f}"
      baseline_key: 
        - lgbm
        - baseline
      split_columns: true
