data_module: 
  _target_: ptls.data_load.data_module.rtd_data_module.RtdDataModuleTrain
  type: map
  setup: 
    col_id: client_id
    dataset_files: 
      data_path: ${hydra:runtime.cwd}/data/train_trx.parquet
    split_by: files
    valid_size: 0.05
    valid_split_seed: 42
  train: 
    min_seq_len: 30
    augmentations: 
      - 
        - AllTimeShuffle
        - {}
      - 
        - DropoutTrx
        - 
          trx_dropout: 0.01
      - 
        - SeqLenLimit
        - 
          max_seq_len: 800
    num_workers: 8
    batch_size: 256
  valid: 
    augmentations: 
      - 
        - SeqLenLimit
        - 
          max_seq_len: 800
    num_workers: 16
    batch_size: 256
  replace_token: 
    replace_prob: 0.15
    skip_first: 1

seed_everything: 42

trainer: 
  gpus: 1
  auto_select_gpus: false
  max_epochs: 20
  enable_checkpointing: false
  deterministic: true

logger_name: rtd_model

pl_module:
  _target_: ptls.frames.bert.RtdModule
  seq_encoder:
    _target_: ptls.nn.RnnSeqEncoder
    trx_encoder: 
      _target_: ptls.nn.TrxEncoder
      norm_embeddings: false
      embeddings_noise: 0.003
      embeddings: 
        level_3: 
          in: 200
          out: 16
        level_4: 
          in: 800
          out: 16
        segment_id: 
          in: 120
          out: 16
      numeric_values: 
        trn_sum_from_iss: identity
        netto: identity
        regular_points_received: identity
    type: gru
    hidden_size: 400
    bidir: false
    trainable_starter: static
  lr_scheduler_partial:
    _partial_: true
    _target_: torch.optim.lr_scheduler.StepLR
    ReduceLROnPlateau: true
    patience: 3
  optimizer_partial:
    _partial_: true
    _target_: torch.optim.Adam
    lr: 0.002
    weight_decay: 0.0

model_path: models/rtd_model_ft.p

inference_dataloader: 
  col_id: client_id
  dataset_files: 
    - ${hydra:runtime.cwd}/data/train_trx.parquet
    - ${hydra:runtime.cwd}/data/test_trx.parquet
  SeqLenLimit: 
    max_seq_len: 800
  loader: 
    num_workers: 4
    batch_size: 1000

output: 
  path: ${hydra:runtime.cwd}/data/rtd_embeddings
  format: pickle
