data_module: 
  _target_: ptls.data_load.data_module.cls_data_module.ClsDataModuleTrain
  type: map
  setup: 
    dataset_files: 
      train_data_path: ${hydra:runtime.cwd}/data/train_trx.parquet
      test_data_path: ${hydra:runtime.cwd}/data/test_trx.parquet
    col_id: game_session
    col_id_dtype: str
    col_target: accuracy_group
    split_by: embeddings_validation
    fold_info: ${hydra:runtime.cwd}/conf/embeddings_validation.work/folds/folds.json
  train: 
    min_seq_len: 1
    augmentations: 
      - 
        - RandomSlice
        - 
          min_len: 150
          max_len: 200
      - 
        - DropoutTrx
        - 
          trx_dropout: 0.005
    num_workers: 16
    batch_size: 64
  valid: 
    augmentations: 
      - 
        - SeqLenLimit
        - 
          max_seq_len: 1200
    num_workers: 16
    batch_size: 512

embedding_validation_results: 
  model_name: nn
  feature_name: cpc_v2_finetuning
  output_path: ${hydra:runtime.cwd}/results/cpc_v2_finetuning_results.json

seed_everything: 42

trainer: 
  gpus: 1
  auto_select_gpus: false
  max_epochs: 25
  log_every_n_steps: 10
  enable_checkpointing: false
  deterministic: true

logger_name: cpc_v2_finetuning

pretrained_encoder_path: ${hydra:runtime.cwd}/../../artifacts/scenario_bowl2019/cpc_v2_model.p
pretrained_module_cls:
  _target_: hydra.utils.get_class
  path: ptls.lightning_modules.cpc_v2_module.CpcV2Module

pl_module:
  _target_: ptls.frames.supervised.SequenceToTarget
  metric_list:
    accuracy:
      _target_: torchmetrics.Accuracy

  pretrained_lr: 0.0001
  head:
    _target_: ptls.nn.Head
    input_size: 777
    objective: classification
    num_classes: 4
  loss:
    _target_: torch.nn.NLLLoss
  optimizer_partial:
    _partial_: true
    _target_: torch.optim.Adam
    lr: 0.001
    weight_decay: 0.0
  lr_scheduler_partial:
    _partial_: true
    _target_: torch.optim.lr_scheduler.StepLR
    step_size: 10
    gamma: 0.1
