conf_path: conf/cpc_v2_embeddings_validation_baselines_unsupervised.yaml

environment: 
  work_dir: embeddings_validation.work

report_file: ${hydra:runtime.cwd}/results/scenario_bowl_baselines_unsupervised_cpc_v2.txt

target: 
  file_name: ${hydra:runtime.cwd}/data/train_labels.csv
  cols_id: 
    - game_session
  cols_id_type: 
    - str
  col_target: accuracy_group
  drop_duplicated_ids: true

split: 
  fit_ids: true
  train_id: 
    file_name: ${hydra:runtime.cwd}/data/train_labels.csv
  test_id: 
    file_name: ${hydra:runtime.cwd}/data/test_ids.csv
  cv_split_count: 5
  is_stratify: true
  random_state: 42

external_scores: {}

models: 
  lgbm: 
    enabled: true
    model:
      _target_: lightgbm.LGBMClassifier
      n_estimators: 1000
      boosting_type: gbdt
      objective: multiclass
      metric: multi_error
      learning_rate: 0.01
      subsample: 0.75
      subsample_freq: 1
      colsample_bytree: 0.75
      max_depth: 12
      reg_lambda: 1
      reg_alpha: 1
      min_child_samples: 50
      num_leaves: 21
      random_state: 42
      n_jobs: 4
    cpu_count: 4
    preprocessing: 
      - _target_: sklearn.preprocessing.MaxAbsScaler

metrics: 
  accuracy: 
    enabled: true
    score_func: sklearn.metrics.accuracy_score
    scorer_params: 
      needs_proba: false

features: 
  baseline: 
    enabled: true
    read_params: 
      file_name: ${hydra:runtime.cwd}/data/agg_feat_embed.pickle
    target_options: {}

report: 
  is_check_train: false
  error_handling: fail
  print_all_metrics: false
  metrics: 
    accuracy: 
      float_format: "{:.3f}"
      baseline_key: 
        - lgbm
        - baseline
      split_columns: true
