data_module: 
  _target_: ptls.data_load.data_module.coles_data_module.ColesDataModuleTrain
  type: map
  setup: 
    col_id: game_session
    dataset_files: 
      data_path: ${hydra:runtime.cwd}/data/train_trx.parquet
    split_by: files
    valid_size: 0.05
    valid_split_seed: 42
  train: 
    min_seq_len: 25
    augmentations: 
      - 
        - DropoutTrx
        - 
          trx_dropout: 0.01
      - 
        - SeqLenLimit
        - 
          max_seq_len: 2500
    split_strategy: 
      split_strategy: SampleSlices
      split_count: 5
      cnt_min: 100
      cnt_max: 500
    num_workers: 16
    batch_size: 256
  valid: 
    augmentations: 
      - 
        - SeqLenLimit
        - 
          max_seq_len: 2500
    split_strategy: 
      split_strategy: SampleSlices
      split_count: 5
      cnt_min: 100
      cnt_max: 500
    num_workers: 16
    batch_size: 256

seed_everything: 42

trainer: 
  gpus: 1
  auto_select_gpus: false
  max_epochs: 100
  enable_checkpointing: false
  deterministic: true

logger_name: mles_model

pl_module:
  _target_: ptls.frames.coles.CoLESModule
  validation_metric:
    _target_: ptls.frames.coles.metric.BatchRecallTopK
    K: 4
    metric: cosine
  seq_encoder:
    _target_: ptls.nn.RnnSeqEncoder
    type: gru
    hidden_size: 100
    bidir: false
    trainable_starter: static
    trx_encoder: 
      _target_: ptls.nn.TrxEncoder
      norm_embeddings: false
      embeddings_noise: 0.003
      embeddings: 
        event_id: 
          in: 500
          out: 16
        event_code: 
          in: 50
          out: 8
        event_type: 
          in: 6
          out: 8
        title: 
          in: 50
          out: 8
        world: 
          in: 6
          out: 8
        correct: 
          in: 4
          out: 2
      numeric_values: {}
  head:
    _target_: ptls.nn.Head
    use_norm_encoder: true
    input_size: ${pl_module.seq_encoder.hidden_size}
  lr_scheduler_partial:
    _partial_: true
    _target_: torch.optim.lr_scheduler.StepLR
    step_size: 30
    gamma: 0.8
  loss:
    _target_: ptls.frames.coles.losses.ContrastiveLoss
    margin: 0.5
    sampling_strategy:
      _target_: ptls.frames.coles.sampling_strategies.HardNegativePairSelector
      neg_count: 2
  optimizer_partial:
    _partial_: true
    _target_: torch.optim.Adam
    lr: 0.002
    weight_decay: 0.0

model_path: models/mles_model.p

inference_dataloader: 
  col_id: game_session
  dataset_files: 
    - ${hydra:runtime.cwd}/data/train_trx.parquet
    - ${hydra:runtime.cwd}/data/test_trx.parquet
  SeqLenLimit: 
    max_seq_len: 1600
  loader: 
    num_workers: 4
    batch_size: 1000

output: 
  path: ${hydra:runtime.cwd}/data/mles_embeddings
  format: pickle
