data_module: 
  _target_: ptls.data_load.data_module.coles_data_module.ColesDataModuleTrain
  type: iterable
  setup: 
    col_id: app_id
    dataset_files: 
      data_path: ${hydra:runtime.cwd}/data/train_trx.parquet
    split_by: files
    valid_size: 0.05
    valid_split_seed: 42
  train: 
    min_seq_len: 25
    buffer_size: 10000
    augmentations: 
      - 
        - DropoutTrx
        - 
          trx_dropout: 0.01
      - 
        - SeqLenLimit
        - 
          max_seq_len: 1200
    num_workers: 16
    batch_size: 64
    split_strategy: 
      split_strategy: SampleSlices
      split_count: 5
      cnt_min: 25
      cnt_max: 150
  valid: 
    augmentations: 
      - 
        - SeqLenLimit
        - 
          max_seq_len: 1200
    num_workers: 16
    batch_size: 1024
    split_strategy: 
      split_strategy: SampleSlices
      split_count: 5
      cnt_min: 25
      cnt_max: 100

seed_everything: 42

trainer: 
  gpus: 1
  auto_select_gpus: 1
  max_steps: 1000
  enable_checkpointing: false
  deterministic: true

logger_name: agg_features_model

pl_module:
  _target_: ptls.frames.coles.CoLESModule
  validation_metric:
    _target_: ptls.frames.coles.metric.BatchRecallTopK
    K: 4
    metric: cosine
  seq_encoder:
    _target_: ptls.seq_encoder.agg_feature_model.AggFeatureSeqEncoder
    embeddings: 
      currency: 
        in: 13
      operation_kind: 
        in: 9
      operation_type: 
        in: 24
      operation_type_group: 
        in: 6
      ecommerce_flag: 
        in: 5
      payment_system: 
        in: 9
      income_flag: 
        in: 5
      mcc: 
        in: 110
      mcc_category: 
        in: 30
      day_of_week: 
        in: 9
      hour: 
        in: 25
      weekofyear: 
        in: 55
    numeric_values: 
      amnt: identity
      hour_diff: log
    was_logified: false
    log_scale_factor: 1
  lr_scheduler_partial:
    _partial_: true
    _target_: torch.optim.lr_scheduler.StepLR
    step_size: 30
    gamma: 0.9025
  head:
    _target_: ptls.nn.Head
    use_norm_encoder: true
    input_size: 777
    use_batch_norm: true
  loss:
    _target_: ptls.frames.coles.losses.ContrastiveLoss
    margin: 0.5
    sampling_strategy:
      _target_: ptls.frames.coles.sampling_strategies.HardNegativePairSelector
      neg_count: 5
  optimizer_partial:
    _partial_: true
    _target_: torch.optim.Adam
    lr: 0.002
    weight_decay: 0.0

model_path: models/agg_features_model.p

inference_dataloader: 
  col_id: app_id
  dataset_files: 
    - ${hydra:runtime.cwd}/data/train_trx.parquet
    - ${hydra:runtime.cwd}/data/test_trx.parquet
  SeqLenLimit: 
    max_seq_len: 1600
  loader: 
    num_workers: 8
    batch_size: 1000
  torch_multiprocessing_sharing_strategy: file_system

output: 
  path: ${hydra:runtime.cwd}/data/agg_feat_embed
  format: pickle
