defaults:
  - _self_
  - dataset_unsupervised/memory_parquet
  - inference/default
  - inference/seq_encoder/pretrained

seed_everything: 42
logger_name: mlmnsp_model
model_path: models/mlmnsp_model.p
embed_file_name: mlmnsp_embeddings

data_module:
  _target_: ptls.frames.PtlsDataModule
  train_data:
    _target_: ptls.frames.bert.MLMNSPDataset
    max_len: 512
    min_len: 128
    data: ${dataset_unsupervised.train}
  valid_data:
    _target_: ptls.frames.bert.MLMNSPDataset
    max_len: 512
    min_len: 128
    data: ${dataset_unsupervised.train}
  train_batch_size: 128
  train_num_workers: 8
  valid_batch_size: 128
  valid_num_workers: 8

trainer:
  gpus: [0]
  auto_select_gpus: false
  max_steps: 64000
  deterministic: false
  checkpoints_every_n_val_epochs: 1
  accumulate_grad_batches: 2
  limit_val_batches: 1000
  val_check_interval: 4000
  enable_progress_bar: true

pl_module:
  _target_: ptls.frames.bert.MLMNSPModule
  total_steps: ${trainer.max_steps}
  hidden_size: 400
  max_lr: 0.00005
  loss_temperature: 2.0
  norm_predict: true
  neg_count: 32
  replace_last_count: 4
  seq_encoder:
    _target_: ptls.nn.LongformerEncoder
    input_size: ${pl_module.hidden_size}
    num_attention_heads: 4
    intermediate_size: 2048
    num_hidden_layers: 8
    attention_window: 16
    max_position_embeddings: 2000
    use_positional_encoding: true
    use_start_random_shift: true
    is_reduce_sequence: false
    add_cls_output: true
  trx_encoder: 
    _target_: ptls.nn.TrxEncoder
    linear_projection_size: ${pl_module.hidden_size}
    orthogonal_init: true
    norm_embeddings: false
    spatial_dropout: 0.1
    embeddings_noise: 0.001
    embeddings: 
      currency: 
        in: 13
        out: 4
      operation_kind: 
        in: 9
        out: 4
      card_type: 
        in: 177
        out: 0
      operation_type: 
        in: 24
        out: 8
      operation_type_group: 
        in: 6
        out: 32
      ecommerce_flag: 
        in: 5
        out: 2
      payment_system: 
        in: 9
        out: 4
      income_flag: 
        in: 5
        out: 2
      mcc: 
        in: 110
        out: 48
      country: 
        in: 26
        out: 0
      city: 
        in: 163
        out: 0
      mcc_category: 
        in: 30
        out: 24
      day_of_week: 
        in: 9
        out: 2
      hour: 
        in: 25
        out: 4
      weekofyear: 
        in: 55
        out: 4
    numeric_values: 
      amnt: identity
      hour_diff: log
