_target_: lightgbm.LGBMClassifier
n_estimators: 500
boosting_type: gbdt
objective: binary
metric: auc
subsample: 0.5
subsample_freq: 1
learning_rate: 0.02
feature_fraction: 0.75
max_depth: 6
lambda_l1: 1
lambda_l2: 1
min_data_in_leaf: 50
random_state: 42
n_jobs: 8
reg_alpha: null
reg_lambda: null
colsample_bytree: null
min_child_samples: null
