conf_path: conf/cpc_v2_embeddings_validation_baselines_supervised.yaml

environment: 
  work_dir: embeddings_validation.work

target: 
  file_name: ${hydra:runtime.cwd}/data/gender_train.csv
  cols_id: 
    - customer_id
  cols_id_type: 
    - int
  col_target: gender

split: 
  fit_ids: true
  train_id: 
    file_name: ${hydra:runtime.cwd}/data/gender_train.csv
  test_id: 
    file_name: ${hydra:runtime.cwd}/data/test_ids.csv
  cv_split_count: 5
  is_stratify: true
  random_state: 42

models: 
  linear: 
    enabled: false
    model:
      _target_: sklearn.linear_model.LogisticRegression
    cpu_count: 1
    preprocessing: 
      - _target_: sklearn.preprocessing.MaxAbsScaler

  lgbm: 
    enabled: true
    model:
      _target_: lightgbm.LGBMClassifier
      n_estimators: 500
      boosting_type: gbdt
      objective: binary
      metric: auc
      subsample: 0.5
      subsample_freq: 1
      learning_rate: 0.02
      feature_fraction: 0.75
      max_depth: 6
      lambda_l1: 1
      lambda_l2: 1
      min_data_in_leaf: 50
      random_state: 42
      n_jobs: 8
      reg_alpha: null
      reg_lambda: null
      colsample_bytree: null
      min_child_samples: null
    cpu_count: 8
    preprocessing: 
      - _target_: sklearn.preprocessing.MaxAbsScaler

  xgb: 
    enabled: false
    model:
      _target_: xgboost.XGBClassifier
      n_jobs: 4
      seed: 42
      n_estimators: 300
    cpu_count: 4
    preprocessing: 
      - _target_: sklearn.preprocessing.MaxAbsScaler

metrics: 
  auroc: 
    enabled: true
    score_func: sklearn.metrics.roc_auc_score
    scorer_params: 
      needs_proba: true
  accuracy: 
    enabled: true
    score_func: sklearn.metrics.accuracy_score
    scorer_params: 
      needs_proba: false

report_file: ${hydra:runtime.cwd}/results/scenario_gender_baselines_supervised_cpc_v2.txt

features: {}

external_scores: 
  fit_target: ${hydra:runtime.cwd}/results/fit_target_results.json
  cpc_v2_finetuning_split_count_20: ${hydra:runtime.cwd}/results/cpc_v2_sub_seq_sampl_strategy_split_count_20.json
  cpc_v2_finetuning_split_count_30: ${hydra:runtime.cwd}/results/cpc_v2_sub_seq_sampl_strategy_split_count_30.json
  cpc_v2_finetuning_split_count_40: ${hydra:runtime.cwd}/results/cpc_v2_sub_seq_sampl_strategy_split_count_40.json
  cpc_v2_finetuning_split_count_50: ${hydra:runtime.cwd}/results/cpc_v2_sub_seq_sampl_strategy_split_count_50.json

report: 
  is_check_train: false
  error_handling: fail
  print_all_metrics: false
  metrics: 
    auroc: 
      float_format: "{:.3f}"
      baseline_key: 
        - nn
        - target_scores
      split_columns: true
