data_module: 
  _target_: ptls.data_load.data_module.cpc_v2_data_module.CpcV2DataModuleTrain
  type: map
  setup: 
    col_id: game_session
    dataset_files: 
      data_path: ${hydra:runtime.cwd}/data/train_trx.parquet
    split_by: files
    valid_size: 0.05
    valid_split_seed: 42
  train: 
    min_seq_len: 200
    augmentations: 
      - 
        - SeqLenLimit
        - 
          max_seq_len: 1200
    split_strategy: 
      split_strategy: SampleUniformBySplitCount
      split_count: 40
    num_workers: 16
    batch_size: 128
  valid: 
    min_seq_len: 200
    augmentations: 
      - 
        - SeqLenLimit
        - 
          max_seq_len: 1200
    split_strategy: 
      split_strategy: SampleUniformBySplitCount
      split_count: 40
    num_workers: 16
    batch_size: 128

seed_everything: 42

trainer: 
  gpus: 1
  auto_select_gpus: false
  max_epochs: 30
  enable_checkpointing: false
  deterministic: true

logger_name: cpc_v2_model

pl_module:
  _target_: ptls.lightning_modules.cpc_v2_module.CpcV2Module
  seq_encoder:
    _target_: ptls.nn.RnnSeqEncoder
    type: gru
    hidden_size: 512
    bidir: false
    trainable_starter: static
  rnn_agg: 
    type: gru
    hidden_size: 256
    bidir: false
    trainable_starter: static
    trx_encoder: 
      _target_: ptls.nn.TrxEncoder
      norm_embeddings: false
      embeddings_noise: 0.003
      embeddings: 
        mcc_code: 
          in: 200
          out: 128
        tr_type: 
          in: 100
          out: 127
      numeric_values: 
        amount: identity
  loss:
    _target_: ptls.lightning_modules.cpc_module.CPC_Loss
    n_forward_steps: 6
    n_negatives: 30
  lr_scheduler_partial:
    _partial_: true
    _target_: torch.optim.lr_scheduler.StepLR
    step_size: 10
    gamma: 0.9525
  optimizer_partial:
    _partial_: true
    _target_: torch.optim.Adam
    lr: 0.0005
    weight_decay: 0.0

model_path: models/cpc_v2_model.p

inference_dataloader: 
  col_id: customer_id
  dataset_files: 
    - ${hydra:runtime.cwd}/data/train_trx.parquet
    - ${hydra:runtime.cwd}/data/test_trx.parquet
  SeqLenLimit: 
    max_seq_len: 1600
  loader: 
    num_workers: 4
    batch_size: 1000

output: 
  path: ${hydra:runtime.cwd}/data/cpc_v2_embeddings
  format: pickle
