conf_path: conf/embeddings_validation_semi_supervised.yaml
environment: 
  work_dir: embeddings_validation_semi_supervised.work
report_file: ${hydra:runtime.cwd}/results/scenario_rosbank__semi_supervised.txt
target: 
  file_name: ${hydra:runtime.cwd}/data/train.csv
  cols_id: 
    - cl_id
  cols_id_type: 
    - int
  col_target: target_flag
  drop_duplicated_ids: true
split: 
  fit_ids: true
  train_id: 
    file_name: ${hydra:runtime.cwd}/data/train.csv
    drop_duplicated_ids: true
  test_id: 
    file_name: ${hydra:runtime.cwd}/data/test_ids.csv
  cv_split_count: 5
  is_stratify: true
  random_state: 42
features: 
  baseline_0225: 
    enabled: true
    read_params: 
      file_name: ${hydra:runtime.cwd}/data/agg_feat_embed.pickle
    target_options: 
      labeled_amount: 225
      random_state: 42
  baseline_0450: 
    enabled: true
    read_params: 
      file_name: ${hydra:runtime.cwd}/data/agg_feat_embed.pickle
    target_options: 
      labeled_amount: 450
      random_state: 42
  baseline_0900: 
    enabled: true
    read_params: 
      file_name: ${hydra:runtime.cwd}/data/agg_feat_embed.pickle
    target_options: 
      labeled_amount: 900
      random_state: 42
  baseline_1800: 
    enabled: true
    read_params: 
      file_name: ${hydra:runtime.cwd}/data/agg_feat_embed.pickle
    target_options: 
      labeled_amount: 1800
      random_state: 42
  baseline_3600: 
    enabled: true
    read_params: 
      file_name: ${hydra:runtime.cwd}/data/agg_feat_embed.pickle
    target_options: 
      labeled_amount: 3600
      random_state: 42
  mles_embeddings_0225: 
    enabled: true
    read_params: 
      file_name: ${hydra:runtime.cwd}/data/mles_embeddings.pickle
    target_options: 
      labeled_amount: 225
      random_state: 42
  mles_embeddings_0450: 
    enabled: true
    read_params: 
      file_name: ${hydra:runtime.cwd}/data/mles_embeddings.pickle
    target_options: 
      labeled_amount: 450
      random_state: 42
  mles_embeddings_0900: 
    enabled: true
    read_params: 
      file_name: ${hydra:runtime.cwd}/data/mles_embeddings.pickle
    target_options: 
      labeled_amount: 900
      random_state: 42
  mles_embeddings_1800: 
    enabled: true
    read_params: 
      file_name: ${hydra:runtime.cwd}/data/mles_embeddings.pickle
    target_options: 
      labeled_amount: 1800
      random_state: 42
  mles_embeddings_3600: 
    enabled: true
    read_params: 
      file_name: ${hydra:runtime.cwd}/data/mles_embeddings.pickle
    target_options: 
      labeled_amount: 3600
      random_state: 42
  cpc_embeddings_0225: 
    enabled: true
    read_params: 
      file_name: ${hydra:runtime.cwd}/data/cpc_embeddings.pickle
    target_options: 
      labeled_amount: 225
      random_state: 42
  cpc_embeddings_0450: 
    enabled: true
    read_params: 
      file_name: ${hydra:runtime.cwd}/data/cpc_embeddings.pickle
    target_options: 
      labeled_amount: 450
      random_state: 42
  cpc_embeddings_0900: 
    enabled: true
    read_params: 
      file_name: ${hydra:runtime.cwd}/data/cpc_embeddings.pickle
    target_options: 
      labeled_amount: 900
      random_state: 42
  cpc_embeddings_1800: 
    enabled: true
    read_params: 
      file_name: ${hydra:runtime.cwd}/data/cpc_embeddings.pickle
    target_options: 
      labeled_amount: 1800
      random_state: 42
  cpc_embeddings_3600: 
    enabled: true
    read_params: 
      file_name: ${hydra:runtime.cwd}/data/cpc_embeddings.pickle
    target_options: 
      labeled_amount: 3600
      random_state: 42
external_scores: 
  t_0225: ${hydra:runtime.cwd}/results/fit_target_0225_results.json
  m_0225: ${hydra:runtime.cwd}/results/mles_finetuning_0225_results.json
  c_0225: ${hydra:runtime.cwd}/results/cpc_finetuning_0225_results.json
  t_0450: ${hydra:runtime.cwd}/results/fit_target_0450_results.json
  m_0450: ${hydra:runtime.cwd}/results/mles_finetuning_0450_results.json
  c_0450: ${hydra:runtime.cwd}/results/cpc_finetuning_0450_results.json
  t_0900: ${hydra:runtime.cwd}/results/fit_target_0900_results.json
  m_0900: ${hydra:runtime.cwd}/results/mles_finetuning_0900_results.json
  c_0900: ${hydra:runtime.cwd}/results/cpc_finetuning_0900_results.json
  t_1800: ${hydra:runtime.cwd}/results/fit_target_1800_results.json
  m_1800: ${hydra:runtime.cwd}/results/mles_finetuning_1800_results.json
  c_1800: ${hydra:runtime.cwd}/results/cpc_finetuning_1800_results.json
  t_3600: ${hydra:runtime.cwd}/results/fit_target_3600_results.json
  m_3600: ${hydra:runtime.cwd}/results/mles_finetuning_3600_results.json
  c_3600: ${hydra:runtime.cwd}/results/cpc_finetuning_3600_results.json
models: 
  lgbm: 
    enabled: true
    model:
      _target_: lightgbm.LGBMClassifier
      n_estimators: 500
      boosting_type: gbdt
      objective: binary
      metric: auc
      subsample: 0.5
      subsample_freq: 1
      learning_rate: 0.02
      feature_fraction: 0.75
      max_depth: 6
      lambda_l1: 1
      lambda_l2: 1
      min_data_in_leaf: 50
      random_state: 42
      n_jobs: 8
      reg_alpha: null
      reg_lambda: null
      colsample_bytree: null
      min_child_samples: null
    cpu_count: 8
    preprocessing: 
      - _target_: sklearn.preprocessing.MaxAbsScaler

metrics: 
  auroc: 
    enabled: true
    score_func: sklearn.metrics.roc_auc_score
    scorer_params: 
      needs_proba: true
  accuracy: 
    enabled: true
    score_func: sklearn.metrics.accuracy_score
    scorer_params: 
      needs_proba: false
report: 
  is_check_train: true
  error_handling: fail
  print_all_metrics: false
  metrics: 
    auroc: 
      float_format: "{:.3f}"
      split_columns: true
    accuracy: 
      float_format: "{:.3f}"
      split_columns: true
    cnt_features: 
      float_format: "{:.0f}"
      keep_columns: 
        - mean
    cnt_samples: 
      float_format: {:9,.0f}
      keep_columns: 
        - mean
