data_module: 
  _target_: ptls.data_load.data_module.coles_data_module.ColesDataModuleTrain
  type: map
  setup: 
    col_id: cl_id
    dataset_files: 
      data_path: ${hydra:runtime.cwd}/data/train_trx.parquet
    split_by: files
    valid_size: 0.05
    valid_split_seed: 42
  train: 
    min_seq_len: 25
    augmentations: 
      - 
        - DropoutTrx
        - 
          trx_dropout: 0.01
    num_workers: 8
    batch_size: 128
    split_strategy: 
      split_strategy: SampleSlices
      split_count: 5
      cnt_min: 15
      cnt_max: 150
  valid: 
    augmentations: []
    num_workers: 16
    batch_size: 256
    split_strategy: 
      split_strategy: SampleSlices
      split_count: 5
      cnt_min: 15
      cnt_max: 75

seed_everything: 42

trainer: 
  gpus: 1
  auto_select_gpus: false
  max_epochs: 60
  enable_checkpointing: false
  deterministic: true

logger_name: mles_proj_head_model

pl_module:
  _target_: ptls.frames.coles.CoLESModule
  validation_metric:
    _target_: ptls.frames.coles.metric.BatchRecallTopK
    K: 4
    metric: cosine
  seq_encoder:
    _target_: ptls.nn.RnnSeqEncoder
    trx_encoder: 
      _target_: ptls.nn.TrxEncoder
      use_batch_norm_with_lens: true
      norm_embeddings: false
      embeddings_noise: 0.0003
      embeddings: 
        mcc: 
          in: 100
          out: 24
        channel_type: 
          in: 4
          out: 4
        currency: 
          in: 4
          out: 4
        trx_category: 
          in: 10
          out: 4
      numeric_values: 
        amount: identity
    type: gru
    hidden_size: 1024
    bidir: false
    trainable_starter: static
  head:
    _target_: ptls.nn.Head
    use_norm_encoder: true
    input_size: ${pl_module.seq_encoder.hidden_size}
    hidden_layers_sizes: [256, 256]
    use_batch_norm: true
  lr_scheduler_partial:
    _partial_: true
    _target_: torch.optim.lr_scheduler.StepLR
    step_size: 10
    gamma: 0.9025
  loss:
    _target_: ptls.frames.coles.losses.ContrastiveLoss
    margin: 0.5
    sampling_strategy:
      _target_: ptls.frames.coles.sampling_strategies.HardNegativePairSelector
      neg_count: 5
  optimizer_partial:
    _partial_: true
    _target_: torch.optim.Adam
    lr: 0.004
    weight_decay: 0.0

model_path: models/mles_proj_head_model.p

inference_dataloader: 
  col_id: cl_id
  dataset_files: 
    - ${hydra:runtime.cwd}/data/train_trx.parquet
    - ${hydra:runtime.cwd}/data/test_trx.parquet
  SeqLenLimit: 
    max_seq_len: 1600
  loader: 
    num_workers: 4
    batch_size: 1000

output: 
  path: ${hydra:runtime.cwd}/data/mles_proj_head_embeddings
  format: pickle
