conf_path: conf/embeddings_validation_short.yaml
environment: 
  work_dir: embeddings_validation.work
report_file: ${hydra:runtime.cwd}/results/scenario_age_pred_short.txt
target: 
  file_name: ${hydra:runtime.cwd}/data/train_target.csv
  cols_id: 
    - client_id
  cols_id_type: 
    - int
  col_target: bins
split: 
  fit_ids: true
  train_id: 
    file_name: ${hydra:runtime.cwd}/data/train_target.csv
  test_id: 
    file_name: ${hydra:runtime.cwd}/data/test_ids_file.csv
  cv_split_count: 5
  is_stratify: true
  random_state: 42
features: 
  baseline:
    enabled: true
    read_params:
      file_name: ${hydra:runtime.cwd}/data/agg_feat_embed.pickle
    target_options: {}
  random_encoder:
    enabled: true
    read_params:
      file_name: ${hydra:runtime.cwd}/data/random_embeddings.pickle
    target_options: {}
  mles_embeddings:
    enabled: false
    read_params: 
      file_name: ${hydra:runtime.cwd}/data/mles_embeddings.pickle
    target_options: {}
external_scores: {}
models: 
  linear: 
    enabled: false
    model:
      _target_: sklearn.linear_model.LogisticRegression
    cpu_count: 1
    preprocessing: 
      - _target_: sklearn.preprocessing.MaxAbsScaler
  lgbm: 
    enabled: true
    model:
      _target_: lightgbm.LGBMClassifier
      n_estimators: 1000
      boosting_type: gbdt
      objective: multiclass
      num_class: 4
      metric: multi_error
      learning_rate: 0.02
      subsample: 0.75
      subsample_freq: 1
      feature_fraction: 0.75
      colsample_bytree: null
      max_depth: 12
      lambda_l1: 1
      reg_alpha: null
      lambda_l2: 1
      reg_lambda: null
      min_data_in_leaf: 50
      min_child_samples: null
      num_leaves: 50
      random_state: 42
      n_jobs: 4
    cpu_count: 4
    preprocessing: 
      - _target_: sklearn.preprocessing.MaxAbsScaler
metrics: 
  accuracy: 
    enabled: true
    score_func: sklearn.metrics.accuracy_score
    scorer_params: 
      needs_proba: false
report: 
  is_check_train: false
  error_handling: fail
  print_all_metrics: false
  metrics: 
    accuracy: 
      float_format: "{:.3f}"
      split_columns: true
