defaults:
  - _self_
  - dataset_unsupervised/parquet
  - inference/default
  - inference/seq_encoder/pretrained_ckpt

seed_everything: 42
logger_name: mles_t_model
model_path: models/mles_t_model.p
embed_file_name: mles_t_embeddings

data_module:
  _target_: ptls.frames.PtlsDataModule
  train_data:
    _target_: ptls.frames.coles.ColesDataset
    splitter:
      _target_: ptls.frames.coles.split_strategy.SampleSlices
      split_count: 5
      cnt_min: 25
      cnt_max: 200
    data: ${dataset_unsupervised.train}
  valid_data:
    _target_: ptls.frames.coles.ColesDataset
    splitter:
      _target_: ptls.frames.coles.split_strategy.SampleSlices
      split_count: 5
      cnt_min: 25
      cnt_max: 100
    data: ${dataset_unsupervised.valid}
  train_batch_size: 64
  train_num_workers: 16
  valid_batch_size: 512
  valid_num_workers: 16

trainer:
  gpus: 1
  auto_select_gpus: false
  max_epochs: 600
  enable_checkpointing: false
  deterministic: true
  checkpoints_every_n_val_epochs: 10

pl_module:
  _target_: ptls.frames.coles.CoLESModule
  validation_metric:
    _target_: ptls.frames.coles.metric.BatchRecallTopK
    K: 4
    metric: cosine
  seq_encoder:
    _target_: ptls.nn.TransformerSeqEncoder
    trx_encoder:
      _target_: ptls.nn.TrxEncoder
      norm_embeddings: false
      embeddings_noise: 0.003
      embeddings:
        trans_date:
          in: 800
          out: 16
        small_group:
          in: 250
          out: 16
      numeric_values: 
        amount_rur: identity
      linear_projection_size: 800
    input_size: 800
    starter: randn
    shared_layers: false
    n_heads: 8
    dim_hidden: 1024
    dropout: 0.1
    n_layers: 8
    use_positional_encoding: true
    use_start_random_shift: true
    max_seq_len: 2000
    use_after_mask: false
    use_src_key_padding_mask: true
    use_norm_layer: true
  head:
    _target_: ptls.nn.Head
    use_norm_encoder: true
  loss:
    _target_: ptls.frames.coles.losses.ContrastiveLoss
    margin: 0.5
    sampling_strategy:
      _target_: ptls.frames.coles.sampling_strategies.HardNegativePairSelector
      neg_count: 5
  optimizer_partial:
    _partial_: true
    _target_: torch.optim.Adam
    lr: 0.0001
    weight_decay: 0.0
  optimizer_trx_weight_decay: 0.0001
  lr_scheduler_partial:
    _partial_: true
    _target_: torch.optim.lr_scheduler.StepLR
    step_size: 30
    gamma: 0.9025
